apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/templates
    repoURL: https://github.com/nanusefue/argocd-example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true